sudo: false
language: node_js
node_js:
  - 'stable'
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^v[0-9].*$/

script:
  - npm run lint
  - npm run semantic-release || true
